- name: Build & Publish Release APK
  # You may pin to the exact commit or the version.
  # uses: pzxmsry/action-release-releaseapk@ba7b20aa82dc51a555e6cee0b2f64a0c1fa8e228
  uses: pzxmsry/action-release-releaseapk@0.0.8
  with:
    # Github secret token to allow automated publishing of APK to release.
    GITHUB_TOKEN: 
    # Github repository branch name.
    REPO_BRANCH: # name
